//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRuleNotification
    {
        public int ID { get; set; }
        public Nullable<int> BusinessRuleID { get; set; }
        public string ReceiverID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual BusinessRule BusinessRule { get; set; }
    }
}
