//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public int ID { get; set; }
        public int TicketID { get; set; }
        public Nullable<System.DateTime> NotifiedTime { get; set; }
        public int ActionType { get; set; }
        public string ActID { get; set; }
        public string BeNotifiedID { get; set; }
        public bool IsForHelpDesk { get; set; }
        public bool IsRead { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual AspNetUser AspNetUser1 { get; set; }
        public virtual Ticket Ticket { get; set; }
    }
}
